#!/bin/bash

export WANDB_DIR=/tmp
export WANDB_CACHE_DIR=/tmp/.cache/wandb

# make result more deterministic
export CUBLAS_WORKSPACE_CONFIG=:4096:8



echo "======== Dataset Preparation ======="
export DATASET_PATHS="/home/space/datasets"

if [[ "$WITH_DATA" = "" ]]; then
   WITH_DATA="cifar100,celeba,imagenet"
fi

if [[ -n "${WITH_DATA// /}" ]]; then
     for DATASET in ${WITH_DATA//,/ }
     do
	     echo "Binding '$DATASET'"
	     if [ ! -f "/tmp/$DATASET.sqfs" ]; then
		 SQFS_PATH="/home/pchormai/datasets/$DATASET.sqfs"
		 echo "> copy $SQFS_PATH to /tmp/"
		 time cp $SQFS_PATH /tmp/
	     fi
	     DATASET_PATH_TO_BIND="/tmp/$DATASET.sqfs:/var/datasets/$DATASET:image-src=/"
	     echo "> $DATASET_PATH_TO_BIND"
	     DATASET_PATHS="$DATASET_PATHS,$DATASET_PATH_TO_BIND"
     done
fi

echo "======== END Dataset Preparation ======="


APPTAINER_BINDPATH=$DATASET_PATHS,`pwd` apptainer run  \
    --nv ./containers/py311v0.0.1.sif \
    "$@"
